# Create NumPy Arrays with Random Numbers

### 1. rand() : the function is used to generate a randomm value between 0 to 1.

In [14]:
import numpy as np

# 1-D
var = np.random.rand(4)  # 4 values of 1 Dimension array

print(var)

[0.56875293 0.24758325 0.70625561 0.59165192]


In [16]:
# 2-D
var1 = np.random.rand(2,5)  # 2 dimensions of 5 random values
print(var1)

[[0.48999063 0.69350247 0.08834164 0.6062308  0.60210631]
 [0.81433892 0.90566738 0.37939911 0.33607453 0.96617415]]


### 2. randn(): generate a random value close to zero either negative or positive.

In [24]:
var2 = np.random.randn(5)
print(var2)

[-1.7199715   3.12254392  1.11084195 -0.07733803 -0.01970291]


### 3. ranf(): returns an array of specified shape and fills it with random floats in the half open interval [0.0,1.0). Here, [ shows that 0.0 will include but ) shows that 1.0 is not included

In [27]:
var3 = np.random.ranf(4)
print(var3)

[0.72261629 0.78995402 0.06015996 0.62218497]


### 4. randint(): generate a random number between a given range by giving minimum and maximum number as parameter and also total number to generate.

In [37]:
# np.random.randint(min,max,total_values)

var4 = np.random.randint(5,20,4)
print(var4)

[ 5  7 11 19]
