# Data Types in NumPy Arrays
| Sr.No. | Data Type | Description                                                                    |
| ------ | --------- | ------------------------------------------------------------------------------ |
| 1      | bool_     | Boolean (True or False) stored as a byte                                       |
| 2      | int_      | Default integer type (same as C long; normally either int64 or int32)          |
| 3      | Intc      | Identical to C int (normally int32 or int64)                                   |
| 4      | Intp      | Integer used for indexing (same as C ssize\_t; normally either int32 or int64) |
| 5      | int8      | Byte (-128 to 127)                                                             |
| 6      | int16     | Integer (-32768 to 32767)                                                      |
| 7      | int32     | Integer (-2147483648 to 2147483647)                                            |
| 8      | int64     | Integer (-9223372036854775808 to 9223372036854775807)                          |
| 9      | uint8     | Unsigned integer (0 to 255)                                                    |
| 10     | uint16    | Unsigned integer (0 to 65535)                                                  |
| 11     | uint32    | Unsigned integer (0 to 4294967295)                                             |
| 12     | uint64    | Unsigned integer (0 to 18446744073709551615)                                   |
| 13     | float     | Shorthand for float64                                                          |
| 14     | float16   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa              |
| 15     | float32   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa            |
| 16     | float64   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa           |
| 17     | complex   | Shorthand for complex128                                                       |
| 18     | complex64 | Complex number, represented by two 32-bit floats (real and imaginary components)|
| 19     | complex128| Complex number, represented by two 64-bit floats (real and imaginary components)|

# dtype

In [6]:
import numpy as np

var = np.array([1,2,3,4])

print("Data type: ", var.dtype)

Data type:  int32


In [8]:
var = np.array([1.0,2.0,3.0,4.0])
print("Data type: ", var.dtype)

Data type:  float64


In [10]:
var = np.array(["A","B","C"])
print("Data type: ", var.dtype)

Data type:  <U1


In [12]:
var = np.array(["A","B","C", 1,2,3,4])
print("Data type: ", var.dtype)

Data type:  <U11


# For converting the Data Types from present to another data type, we can either use the same as above list or we can use shortcuts which is listed below:

### Data Types as Function
##### list of characters that are used to represent dtype in Numpy:

| Character | Data Type Description |
|-----------|---------------------|
| i         | integer             |
| b         | boolean             |
| u         | unsigned integer    |
| f         | float               |
| C         | complex float       |
| m         | timedelta           |
| M         | datetime            |
| O         | object              |
| S         | string              |
| U         | Unicode string      |
| V         | the fixed chunk of memory for other types (void) |


In [23]:
x = np.array([1,2,3,4])
print("Data Type: ", x.dtype)

Data Type:  int32


In [31]:
# Converting int32 to int8

x = np.array([1,2,3,4],dtype = np.int8) 
print("Data Type: ", x.dtype)
print(x)

Data Type:  int8
[1 2 3 4]


In [37]:
# Converting integer to float

x1 = np.array([1,2,3,4],dtype = "f")
print("Data Type: ", x1.dtype)
print(x1)

Data Type:  float32
[1. 2. 3. 4.]


In [47]:
# Converting data type as a function
# int32 to float32
# again float32 to int32

x2 = np.array([1,2,3,4])

new = np.float32(x2)

new_one = np.int_(new)

print("Data Type: ", x2.dtype)
print("Data Type: ", new.dtype)
print("Data Type: ", new_one.dtype)

print(x2)
print(new)
print(new_one)

Data Type:  int32
Data Type:  float32
Data Type:  int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [53]:
# Converting datatype using astype()function

x3 = np.array([1,2,3,4])

new_1 = x3.astype(float)

print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]
