# Arithmetic Operation in Numpy Arrays
| Operation | Expression | Numpy Function      |
|-----------|------------|---------------------|
| Addition  | a + b      | np.add(a,b)         |
| Subtract  | a - b      | np.subtract(a,b)    |
| Multiply  | a * b      | np.multiply(a, b)   |
| Divide    | a / b      | np.divide(a, b)     |
| Modulus   | a % b      | np.mod(a, b)        |
| Power     | a ** b     | np.power(a, b)      |
| Reciprocal| 1 / a      | np.reciprocal(a)    |

## For 1-Dimension Array

In [27]:
import numpy as np

### 1. Addition

In [35]:

# Single number addition using expression

var = np.array([1,2,3,4])

varadd = var + 3

print(varadd)

[4 5 6 7]


In [37]:
# Single number addition using function

var = np.array([1,2,3,4])

varadd = np.add(var,3)

print(varadd)

[4 5 6 7]


In [39]:
# Sum of two arrays using expression

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1 + var2

print(varadd)

[2 4 6 8]


In [41]:
# using Function of array

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = np.add(var1, var2)

print(varadd)

[2 4 6 8]


### 2. Subtract

In [44]:
# Using Expression

var = np.array([1,2,3,4])
varadd = var - 3

print(varadd)

[-2 -1  0  1]


In [53]:
# Using Function
var = np.array([1,2,3,4])
varadd = np.subtract(var,3)

print(varadd)

[-2 -1  0  1]


### 3. Multiply

In [56]:
# Using Expression

var = np.array([1,2,3,4])
varadd = var * 3

print(varadd)

[ 3  6  9 12]


In [58]:
# Using Function
var = np.array([1,2,3,4])
varadd = np.multiply(var,3)

print(varadd)

[ 3  6  9 12]


### 4. Divide

In [16]:
# Using expression

var = np.array([1,2,3,4])
varadd = var / 3

print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [63]:
# Using Function

var = np.array([1,2,3,4])
varadd = np.divide(var,3)

print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


### 5. Modulo

In [66]:
# Using Expression

var = np.array([1,2,3,4])
varadd = var % 3

print(varadd)

[1 2 0 1]


In [68]:
# Using Function

var = np.array([1,2,3,4])
varadd = np.mod(var,3)

print(varadd)

[1 2 0 1]


### 6. Power

In [82]:
# Using expression

var = np.array([1,2,3,4])
varadd = var**3

print(varadd)

[ 1  8 27 64]


In [84]:
# Using Function

var = np.array([1,2,3,4])
varadd = np.power(var,3)

print(varadd)

[ 1  8 27 64]


### 7. Reciprocal

In [97]:
# Using Expression

var = np.array([1,2,3,4])
varadd = 1//var

print(varadd)

[1 0 0 0]


In [93]:
# Using Function

var = np.array([1,2,3,4])
varadd = np.reciprocal(var)

print(varadd)

[1 0 0 0]


## For 2-Dimension Array

In [114]:
# Using Expression

var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])
varadd = var21 + var22

print(varadd)

[[2 4 6 8]
 [2 4 6 8]]


In [112]:
# Using function

var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

varadd = np.add(var21,var22)

print(varadd)

[[2 4 6 8]
 [2 4 6 8]]
