# Arithmetic Functions
| Functions    |
|--------------|
| np.min(x)    |
| np.max(x)    |
| np.argmin(x) |
| np.argmax(x) |
| np.sqrt(x)   |
| np.sin(x)    |
| np.cos(x)    |
| np.cumsum(x) |

In [4]:
import numpy as np

### 1. Minimum and Maximum

In [15]:
var = np.array([2,1,3,4,5,3,2])

print("minimum: ",np.min(var))
print("maximum: ",np.max(var))

minimum:  1
maximum:  5


### 2. Position of Minimum and Maximum

In [18]:
print("minimum: ",np.argmin(var))
print("maximum: ",np.argmax(var))

minimum:  1
maximum:  4


In [24]:
# For 2-D 

var1 = np.array([[2,1,3],[9,5,6]])
print(np.min(var1,axis=0))   # Axis=0 works with Column 

[2 1 3]


In [28]:
print(np.min(var1,axis=1)) # Axis=1 works with Rows

[1 5]


### 3. Square Root

In [31]:
print("square root:", np.sqrt(var))

square root: [1.41421356 1.         1.73205081 2.         2.23606798 1.73205081
 1.41421356]


### 4. Sin and Cos

In [34]:
var2 = np.array([1,30,9])

print(np.sin(var2))
print(np.cos(var2))

[ 0.84147098 -0.98803162  0.41211849]
[ 0.54030231  0.15425145 -0.91113026]


### 5. Cumsum

In [39]:
print(np.cumsum(var2)) # It works as first same value then add this to 2nd value then the added value add with another value like 1, then add to 30 = 31, now 31 add to 9=40

[ 1 31 40]
