### Shape

In [4]:
import numpy as np

var = np.array([[1,2,3,4],[1,2,3,4]])

print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [10]:
# 2-D

var1 = np.array([1,2,3,4], ndmin =4)

print(var1)
print(var1.ndim)
print()
print(var1.shape) # for 4-D

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


### Reshape

In [19]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)
print()

x = var2.reshape(3,2) # 1st parameter is no. of row and 2nd for no. of columns

print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [37]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
print()

x1 = var3.reshape(3,2,2) # 1st parameter is no. of row and 2nd for no. of columns and 3rd one is for total no. of rows and columns

print(x1)
print(x1.ndim)
print()

# For reshape, from 3 to 1 Dimension
one = x1.reshape(-1)
print(one)
print(one.ndim)
print()



[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

