# Broadcasting 
#### Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be used together in arithmetic operations.
<div style="text-align: center;">
    <img src="broadcasting_array.png" alt="My Image" width="300"/>
</div>

In [1]:
import numpy as np

In [9]:
arr1 = np.array([1,2,3])
print(arr1.shape)
print(arr1)
print()

arr2 = np.array([[1],[2],[3]])
print(arr2.shape)
print(arr2)
print()

(3,)
[1 2 3]

(3, 1)
[[1]
 [2]
 [3]]



#### Since the first array have shape (1x3) and the second array have shape (3x1),
#### it means that 1 is present in the both array's shape, so we can now perform any operations on that.

## For addition
<div style="text-align: center;">
    <img src="broadcasting_addition.png" alt="Broadcasting Addition Image" width="300"
</div>

In [34]:
result = arr1 + arr2
print(result)
print()
print(result.shape)

[[2 3 4]
 [3 4 5]
 [4 5 6]]

(3, 3)


### For (2x1) and (2x3): We can perform the operation because there is '1' present in between them

In [45]:
x = np.array([[1],[2]])
print(x.shape)

y = np.array([[1,2,3],[1,2,3]])
print(y.shape)
print()

print(x+y)

(2, 1)
(2, 3)

[[2 3 4]
 [3 4 5]]
