# Indexing
<div style="text-align: center;">
    <img src="Images\Indexing.png" alt="Indexing Image" width="300"/>
</div>

In [6]:
import numpy as np

### For 1-D

In [12]:
var = np.array([9,8,7,6])
# Index no.     0,1,2,3
# -ve          -4,-3,-2,-1

print(var[1])
print(var[-2])

8
7


### For 2-D
##### Note: For 2-D, first parameter is for the row no. and second for the index no.

In [21]:
var1 = np.array([[9,8,7],[4,5,6]])

print(var1)
print(var1.ndim)
print()

print(var1[0,1]) # '0' denotes the first row and '1' denotes the value at index 1 of first row

[[9 8 7]
 [4 5 6]]
2

8


### For 3-D

In [33]:
var2 = np.array([[[1,2],[6,7]]])

print(var2)
print(var2.ndim)

print()
print(var2[0,1])
print()
print(var2[0,1,1])

[[[1 2]
  [6 7]]]
3

[6 7]

7


# Slicing
### For 1-D

In [56]:
# In slicing, [start:stop:step] , Note: step is optional

import numpy as np

var = np.array([1,2,3,4,5,6,7])
# Index no.     0,1,2,3,4,5,6

print(var)
print()

print("2 to 5 : ", var[1:5]) # 5 is not included

print("2 to End: ", var[1:])

print("Start to 5 : ", var[:5]) # 5 not included, it will run from start to 5-1

print("stop : ", var[::2]) # 2 is the step

print("stop : ", var[1:5:2]) # 2 is the step

[1 2 3 4 5 6 7]

2 to 5 :  [2 3 4 5]
2 to End:  [2 3 4 5 6 7]
Start to 5 :  [1 2 3 4 5]
stop :  [1 3 5 7]
stop :  [2 4]


### For 2-D

In [62]:
var1 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(var1)
print()

print("8 to 5: ", var1[1,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

8 to 5:  [8 7 6 5]


In [64]:
print("13 to 15: ", var1[2,2:])

13 to 15:  [13 14 15]
