# Iteration of array using:
1) loop
2) function

# 1. loop
#### 1-D

In [9]:
import numpy as np

var = np.array([9,8,7,6,5,4])
print(var)
print()

for i in var:
    print(i)

[9 8 7 6 5 4]

9
8
7
6
5
4


#### 2-D

In [12]:
var1 = np.array([[9,8,2,4],[1,2,3,4]])
print(var1)
print()

for k in var1:
    for l in k:
        print(l)

[[9 8 2 4]
 [1 2 3 4]]

9
8
2
4
1
2
3
4


#### 3-D 

In [21]:
var3 = np.array([[[1,2,3,4],[4,2,7,5]]])
print(var3)
print(var3.ndim)
print()

for i in var3:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4]
  [4 2 7 5]]]
3

1
2
3
4
4
2
7
5


# 2. Function
- nditer()

In [28]:
var3 = np.array([[[1,2,3,4],[4,2,7,5]]])
print(var3)
print(var3.ndim)
print()

for i in np.nditer(var3):
    print(i)

[[[1 2 3 4]
  [4 2 7 5]]]
3

1
2
3
4
4
2
7
5


In [30]:
# For data type change

var3 = np.array([[[1,2,3,4],[4,2,7,5]]])
print(var3)
print(var3.ndim)
print()

for i in np.nditer(var3, flags=["buffered"],op_dtypes=["S"]): # Buffered means a storage is created to store the data, & "S" is for the data type conversion in the String
    print(i)

[[[1 2 3 4]
  [4 2 7 5]]]
3

b'1'
b'2'
b'3'
b'4'
b'4'
b'2'
b'7'
b'5'


#### Iterate with indexing number using a function:
- ndenumerate()

In [37]:
# Iterate with indexing number too

var3 = np.array([[[1,2,3,4],[4,2,7,5]]])
print(var3)
print(var3.ndim)
print()

for i in np.ndenumerate(var3):
    print(i)

[[[1 2 3 4]
  [4 2 7 5]]]
3

((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 0, 2), 3)
((0, 0, 3), 4)
((0, 1, 0), 4)
((0, 1, 1), 2)
((0, 1, 2), 7)
((0, 1, 3), 5)
