# Join Array
## Functions:
1. concatenate((1st_array, 2nd_array))
## For 1-D 

In [11]:
import numpy as np

var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])

print(var)
print(var1)
print()
ar = np.concatenate((var,var1))

print(ar)

[1 2 3 4]
[9 8 7 6]

[1 2 3 4 9 8 7 6]


## For 2-D
- concatenate((1st_array,2nd_array), axis) ====> axis can be 0 or 1, 0 denotes column side, 1 denotes row side

In [13]:
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[9,8],[7,6]])

ar_new = np.concatenate((vr,vr1), axis=1)

print(vr)
print()
print(vr1)
print()
print(ar_new)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2 9 8]
 [3 4 7 6]]


In [19]:
ar_new = np.concatenate((vr,vr1), axis=0)

print(vr)
print()
print(vr1)
print()
print(ar_new)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2]
 [3 4]
 [9 8]
 [7 6]]


2. stack() =====> it works on the basis of axis

In [23]:
var_1 = np.array([1,2,3,4])
var_2= np.array([9,8,7,6])

print(var_1)
print(var_2)
print()
a_new = np.stack((var_1,var_2), axis=1)

print(a_new)

[1 2 3 4]
[9 8 7 6]

[[1 9]
 [2 8]
 [3 7]
 [4 6]]


## If we want to join the arrays without giving axis, we use:
- hstack((arr1,arr2)) ====> It joins the array via horizontally (row)
- vstack((arr1,arr2)) ====> It joins the array via vertically (column)
- dstack((arr1,arr2)) ====> It joins the array via height (height)

#### hstack()

In [29]:
var_3 = np.array([1,2,3,4])
var_4= np.array([9,8,7,6])

print(var_3)
print(var_4)
print()
aa_new = np.hstack((var_1,var_2))

print(aa_new)

[1 2 3 4]
[9 8 7 6]

[1 2 3 4 9 8 7 6]


#### vstack()

In [38]:
var_5 = np.array([1,2,3,4])
var_6= np.array([1,8,7,6])

print(var_5)
print(var_6)
print()
aaa_new = np.vstack((var_5,var_6))

print(aaa_new)

[1 2 3 4]
[1 8 7 6]

[[1 2 3 4]
 [1 8 7 6]]


#### dstack()

In [43]:
var_7 = np.array([1,2,3,4])
var_8= np.array([1,8,7,6])

print(var_7)
print(var_8)
print()
aaaa_new = np.dstack((var_7,var_8))

print(aaaa_new)

[1 2 3 4]
[1 8 7 6]

[[[1 1]
  [2 8]
  [3 7]
  [4 6]]]


# Split Array
### Functions:
1. array_split(array,no.of_required_array)
## 1-D 

In [62]:
a = np.array([1,2,3,4,5,6])

print(a)

ar = np.array_split(a,3)
print()
print(ar)
print(type(ar))

print(ar[2]) # at index no. 2

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[5 6]


## 2-D

In [67]:
b = np.array([[1,2],[3,4],[5,6]])

print(b)

ar1 = np.array_split(b,3)
print()
print(ar1)
print(type(ar1))

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
<class 'list'>


### Split by giving axis

In [70]:
b = np.array([[1,2],[3,4],[5,6]])

print(b)

ar2 = np.array_split(b,3,axis=1)
print()
print(ar2)
print(type(ar2))

[[1 2]
 [3 4]
 [5 6]]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]
<class 'list'>
