# NumPy Arrays Functions 
- (Search, Sort, Search Sorted, Filter)

## 1. Search Array :- Search an array for a certain value, and return the indexes that get a match
- Note: we use "where" keyword for the searching i.e where()

In [5]:
import numpy as np

var = np.array([1,2,3,4,2,5,2,5,6,7])
# indexes       0,1,2,3,4,5,6,7,8,9

x = np.where( var == 2)

print(x)

(array([1, 4], dtype=int64),)


In [9]:
var = np.array([4,2,3,4,2,5,2,5,6,7])
# indexes       0,1,2,3,4,5,6,7,8,9

x = np.where( var%2 == 0)

print(x)

(array([0, 1, 3, 4, 6, 8], dtype=int64),)


## 2. Search Sorted Array: which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.
- searchsorted(array, element_to_put_inside_the_array) ===> This will show the possible position for the element in the array by returning the index no.

In [18]:
var1 = np.array([1,2,3,4,6,7,8])
# indexes        0,1,2,3,4,5,6

x1 = np.searchsorted(var1, 5) # 5 is possible at index 4 in the above sorted array

print(x1)

4


- we can use "side" parameter which is optional : It means it will search from right side to left

In [20]:
var2 = np.array([1,2,3,4,6,7,8,9,10,11,12])
# indexes        0,1,2,3,4,5,6,7,8,9,10,11

x2 = np.searchsorted(var1, 5, side="right") 
print(x2)

4


- we can provide the list too for the searching 

In [30]:
var3 = np.array([1,2,3,4,6,7,8,9,10,11])
# indexes        0,1,2,3,4,5,6,7,8,9

x3 = np.searchsorted(var3, [5,6,3] , side="right") 
print(x3)

[4 5 3]


## 3. Sort Array: Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

- For numeric

In [42]:
var4 = np.array([4,2,3,11,6,10,8,9,10,11,1])

x4 = np.sort(var4)
print(x4)

# or we can direct print 
# print(np.sort(var4))

[ 1  2  3  4  6  8  9 10 10 11 11]


- For alphabet

In [45]:
var5 = np.array(["a","s","d","f"])

print(np.sort(var5))

['a' 'd' 'f' 's']


- For 2-D array

In [52]:
var6 = np.array([[31,4,6],[7,90,10],[10,1,12]])

print(np.sort(var6))

[[ 4  6 31]
 [ 7 10 90]
 [ 1 10 12]]


## Filter Array: Getting some elements out of an existing array and creating a new array out of them.
- we have to pass the True or False according to the index number: True means to have the element filtered and False means the element which we don't want to have in new array

In [56]:
arr = np.array(["a","s","d","f"])

fil = [True,False,False,True] 

new_arr = arr[fil]

print(new_arr)

['a' 'f']
