# Arithmetic Functions
1. Shuffle
2. Unique
3. Resize
4. Flatten
5. Ravel

## 1. Shuffle := It shuffles the array 

In [14]:
import numpy as np

var = np.array([1,2,3,4,5])

np.random.shuffle(var)

print(var)

[1 4 2 5 3]


## 2. Unique :- It ignores the duplicate elements

In [10]:
var1 = np.array([1,2,3,4,2,5,2,6,2,7])

x = np.unique(var1)
print(x)

[1 2 3 4 5 6 7]


- To print the index number 

In [18]:
x = np.unique(var1, return_index=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9], dtype=int64))


- To print counting of the elements

In [21]:
x = np.unique(var1, return_index=True, return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9], dtype=int64), array([1, 4, 1, 1, 1, 1, 1], dtype=int64))


## 3. Resize :- Change the size of array

In [34]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(2,3)) # 2 rows and 3 columns

print(y)

[[1 2 3]
 [4 5 6]]


## 4. Flatten :- Convert 2-D to 1-D array
- Always returns a copy of the array.
- Any changes made to the flattened array do NOT affect the original array.
- Slower compared to ravel() because it allocates new memory.

In [46]:
var3 = np.array([[9,3],[5,4],[4,2]])
print(var3)
print()

print(var3.flatten()) # It will do row wise

[[9 3]
 [5 4]
 [4 2]]

[9 3 5 4 4 2]


#### Order for the Flatten
Order : {'C', 'F', 'A', 'K'}, Optional  

- **'C'** means to flatten in row-major (C-style) order.  

- **'F'** means to flatten in column-major (Fortran-style) order.  

- **'A'** means to flatten in column-major order if `a` is Fortran *contiguous*  
  in memory, row-major order otherwise.  

- **'K'** means to flatten `a` in the order the elements occur in memory.  

- The default is **'C'**.  


In [52]:
print(var3)
print()
print(var3.flatten(order="F"))

[[9 3]
 [5 4]
 [4 2]]

[9 5 4 3 4 2]


## 5. Ravel :- It is similar to the flatten
- Returns a view (reference) of the array whenever possible.
- If a view is returned, changes in the raveled array WILL affect the original array.
- If not possible, it returns a copy.
- Faster, more memory-efficient.

In [63]:
var4 = np.array([[9,2],[5,4],[4,2]])
print(var4)
print()

print(var4.ravel(order="F"))

[[9 2]
 [5 4]
 [4 2]]

[9 5 4 2 4 2]
