# Insert
- insert(array, (index_numbers), element))
### 1-D

In [36]:
import numpy as np

var = np.array([1,2,3,4])
print(var)
print()

v = np.insert(var, 2, 40)

# or we can use append funcction
# v1 = np.append(var, 40)

print(v)

[1 2 3 4]

[ 1  2 40  3  4]


In [38]:
w = np.insert(var, (1,2), (50,40))
print(w)

[ 1 50  2 40  3  4]


- If we provide float value, then it will not accept but converts into the integer

In [41]:
x = np.insert(var, (1,2), 56.7)
print(x)

[ 1 56  2 56  3  4]


## 2-D
- insert(array, index, element, axis) :- axis 0 means rows, 1 means columns 

In [44]:
var1 = np.array([[1,2,3],[1,2,3]])

v1 = np.insert( var1, 2, 60, axis = 1)

# or we can use append funcction
# v1 = np.append(var1, [[45,44,23]], axis=1)

print(v1)

[[ 1  2 60  3]
 [ 1  2 60  3]]


# Delete

In [49]:
import numpy as np

var1 = np.array([1,2,3,4])
print(var1)
print()

d = np.delete(var1,2)
print(d)


[1 2 3 4]

[1 2 4]
