<img src="Images/matrix_array.png" alt="Matrix Array Image" width=800/>

# Matrix :- 
- Addition

In [27]:
import numpy as np

var = np.matrix([[1,2],[1,2]])
var2 = np.matrix([[1,2],[1,2]])

print(var+var2)

[[2 4]
 [2 4]]


- Subtraction

In [32]:
print(var-var2)

[[0 0]
 [0 0]]


- Multiplication

In [51]:
print(var*var2) 

# or

print()
print(var.dot(var2))

[[3 6]
 [3 6]]

[[3 6]
 [3 6]]


# Array :- 
- Multiplication

In [54]:
var3 = np.array([[1,2],[1,2]])
var4 = np.array([[1,2],[1,2]])

print(var3*var4)

[[1 4]
 [1 4]]


- Addition

In [57]:
print(var3+var4)

[[2 4]
 [2 4]]


- Substraction

In [60]:
print(var3-var4)

[[0 0]
 [0 0]]
