# Matrix Function in NumPy Arrays
1. Transpose
2. Swapaxes
3. Inverse
4. Power
5. Determinate

## 1. Transpose

<img src="Images/transpose_matrix.png" alt="Transpose Matrix" width="800" />

In [61]:
import numpy as np

var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()

print(np.transpose(var))
print()

#Shortcut
print(var.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


## 2. Swapaxes :- Row to column and Column to row conversion
<img src="Images/swapaxes_matrix.png" alt="Swapaxes Image" width="800"/>

In [64]:
print(np.swapaxes(var,0,1)) # 0 and 1 are the axis, 0 to 1 conversion is done here

[[1 4]
 [2 5]
 [3 6]]


In [65]:
var2 = np.matrix([[1,2],[3,4]])
print(var2)
print()
print(np.swapaxes(var2,0,1))
print()
print(np.swapaxes(var2,1,0))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]

[[1 3]
 [2 4]]


## 3. Inverse
- linalg.inv()
<img src="Images/inverse_matrix.png" alt="Inverse Image" width="800"/>

In [67]:
var3 = np.matrix([[1,2],[3,4]])
print(var3)
print()

print(np.linalg.inv(var3))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


## 4. Power
<img src="Images/power_matrix.png" alt="Power of matrix" width="800"/>

In [69]:
var4 = np.matrix([[1,2],[3,4]])
print(var4)
print()

print(np.linalg.matrix_power(var4,2))
print()

print(np.linalg.matrix_power(var4,0))
print()

print(np.linalg.matrix_power(var4,-2))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


## 5. Determinate
<img src="Images/determinate_matrix.png" alt="Determinate Image" width="800"/>

In [71]:
var5 = np.matrix([[1,2,3],[3,4,3],[1,2,3]])
print(var5)
print()
print(np.linalg.det(var5))

[[1 2 3]
 [3 4 3]
 [1 2 3]]

0.0
